/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutostartToggle: typeof import('./src/components/AutostartToggle.vue')['default']
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    LayoutDropdownMenu: typeof import('./src/components/layout/DropdownMenu.vue')['default']
    LayoutTitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    PurchaseButton: typeof import('./src/components/PurchaseButton.vue')['default']
    RouteLineSelector: typeof import('./src/components/RouteLineSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharpForm: typeof import('./src/components/sharp/Form.vue')['default']
    SharpModal: typeof import('./src/components/sharp/Modal.vue')['default']
  }
}
